//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpnManagerDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogConenction
    {
        public long Id { get; set; }
        public long Id_ConnectionPlant { get; set; }
        public string UserName { get; set; }
        public System.DateTime LastConenctionTime { get; set; }
        public bool ConncetionSuccesful { get; set; }
        public string VirtualMachineName { get; set; }
    }
}
