//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpnManagerDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VpnType
    {
        public VpnType()
        {
            this.Plant = new HashSet<Plant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string WorkOnMachine { get; set; }
    
        public virtual ICollection<Plant> Plant { get; set; }
    }
}
